"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";

const HERO_PILLARS = [
  { name: "Schema markup", target: 72, color: "#a8ff57" },
  { name: "Content quality", target: 58, color: "#57b8ff" },
  { name: "Technical SEO", target: 81, color: "#ffb347" },
  { name: "Trust signals", target: 44, color: "#ff7eb3" },
] as const;

const SCAN_STEPS = [
  "Initializing crawler...",
  "Extracting JSON-LD schema...",
  "Analyzing content structure...",
  "Running technical checks...",
  "Evaluating trust signals...",
  "Computing AI readiness score...",
] as const;

const SCAN_PCTS = [10, 28, 47, 65, 82, 98] as const;

const FAQ_ITEMS = [
  {
    q: "How is this different from traditional SEO tools like Ahrefs or Semrush?",
    a: "Traditional SEO tools optimize for Google's PageRank algorithm — backlinks, keyword density, crawl budget. AI search engines like ChatGPT and Perplexity work completely differently. They parse content semantically, rely heavily on structured data, and evaluate authority through E-A-T signals. We're built specifically for this new paradigm.",
  },
  {
    q: "What exactly do I get with the $29 full audit?",
    a: "You get a detailed breakdown of all 30+ checks across the four pillars, a prioritized fix roadmap, copy-paste JSON-LD schema code tailored to your site, content structure recommendations, and a downloadable PDF report. You also get 30-day access to re-scan after making changes.",
  },
  {
    q: "Which AI search engines does this optimize for?",
    a: "Our checks are validated against ChatGPT's browsing behavior, Perplexity's citation patterns, Google's SGE (AI Overviews), Microsoft Copilot, and Claude. The underlying optimization principles — structured data, semantic clarity, authority signals — apply across all major AI search platforms.",
  },
  {
    q: "Can you scan JavaScript-rendered websites?",
    a: "Yes. We use a full headless rendering pipeline so we see your site exactly as AI crawlers do — including content generated by React, Vue, Next.js, or any other JavaScript framework. Static HTML sites are also fully supported.",
  },
  {
    q: "Is the free scan actually useful or just a teaser?",
    a: "The free scan gives you your real score and identifies your top 3 critical issues — enough to understand where you stand and whether investing in the full audit makes sense. We deliberately make it useful, not a fake preview. If your site scores 85+, you probably don't need to pay.",
  },
  {
    q: "What's your refund policy?",
    a: "We offer a full refund within 48 hours if the audit doesn't surface any actionable issues for your site. Given that 73% of sites fail basic AI readiness checks, this is rare — but we stand behind it. Email us directly at support@auditai.com.",
  },
] as const;

function animateValue(
  from: number,
  to: number,
  duration: number,
  onUpdate: (value: number) => void
) {
  const start = performance.now();
  let frameId = 0;

  const step = (now: number) => {
    const t = Math.min((now - start) / duration, 1);
    const ease = 1 - Math.pow(1 - t, 3);
    onUpdate(Math.round(from + (to - from) * ease));
    if (t < 1) {
      frameId = requestAnimationFrame(step);
    }
  };

  frameId = requestAnimationFrame(step);

  return () => cancelAnimationFrame(frameId);
}

export default function ExactLanding() {
  const router = useRouter();
  const [heroUrl, setHeroUrl] = useState("");
  const [ctaUrl, setCtaUrl] = useState("");
  const [heroScore, setHeroScore] = useState(0);
  const [pillarScores, setPillarScores] = useState([0, 0, 0, 0]);
  const [pillarWidths, setPillarWidths] = useState([0, 0, 0, 0]);
  const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(null);

  const [scanActive, setScanActive] = useState(false);
  const [scanId, setScanId] = useState<string | null>(null);
  const [scanUrlDisplay, setScanUrlDisplay] = useState("https://yoursite.com");
  const [scanStepText, setScanStepText] = useState("Initializing crawler...");
  const [scanBarWidth, setScanBarWidth] = useState(0);
  const [scanStepIndex, setScanStepIndex] = useState(-1);
  const [scanError, setScanError] = useState<string | null>(null);

  const pollTimerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const scanDoneTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  useEffect(() => {
    const timeouts: Array<ReturnType<typeof setTimeout>> = [];
    const cancels: Array<() => void> = [];

    const initTimeout = setTimeout(() => {
      cancels.push(animateValue(0, 67, 1800, setHeroScore));

      HERO_PILLARS.forEach((pillar, index) => {
        const timeout = setTimeout(() => {
          setPillarWidths((prev) =>
            prev.map((value, i) => (i === index ? pillar.target : value))
          );

          cancels.push(
            animateValue(0, pillar.target, 1000, (value) => {
              setPillarScores((prev) =>
                prev.map((score, i) => (i === index ? value : score))
              );
            })
          );
        }, 1000 + index * 200);

        timeouts.push(timeout);
      });
    }, 900);

    timeouts.push(initTimeout);

    return () => {
      timeouts.forEach((timeout) => clearTimeout(timeout));
      cancels.forEach((cancel) => cancel());
    };
  }, []);

  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add("visible");
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1 }
    );

    const elements = Array.from(document.querySelectorAll(".reveal"));
    elements.forEach((el) => observer.observe(el));

    return () => {
      elements.forEach((el) => observer.unobserve(el));
      observer.disconnect();
    };
  }, []);

  useEffect(() => {
    return () => {
      if (pollTimerRef.current) clearInterval(pollTimerRef.current);
      if (scanDoneTimeoutRef.current) clearTimeout(scanDoneTimeoutRef.current);
    };
  }, []);

  useEffect(() => {
    if (!scanId || !scanActive) return;

    const pollStatus = async () => {
      try {
        const response = await fetch(`/api/scan/${scanId}/status`);
        const data = await response.json();

        if (!response.ok) {
          setScanError(data.error || "Scan not found");
          setScanStepText(`✗ Error: ${data.error || "Scan not found"}`);
          if (pollTimerRef.current) clearInterval(pollTimerRef.current);
          return;
        }

        if (typeof data.step === "number") {
          setScanStepIndex(data.step);
          setScanBarWidth(
            typeof data.progress === "number"
              ? data.progress
              : SCAN_PCTS[data.step] || 0
          );
        }

        if (typeof data.stepText === "string" && data.stepText.length > 0) {
          setScanStepText(data.stepText);
        }

        if (data.status === "complete") {
          setScanBarWidth(100);
          setScanStepText("✓ Analysis complete!");
          if (pollTimerRef.current) clearInterval(pollTimerRef.current);
          scanDoneTimeoutRef.current = setTimeout(() => {
            setScanActive(false);
            router.push(`/scan/${scanId}`);
          }, 1200);
        }

        if (data.status === "error") {
          const message = data.error || "Unknown error";
          setScanError(message);
          setScanStepText(`✗ Error: ${message}`);
          if (pollTimerRef.current) clearInterval(pollTimerRef.current);
        }
      } catch {
        setScanError("Failed to fetch scan status");
        setScanStepText("✗ Error: Failed to fetch scan status");
        if (pollTimerRef.current) clearInterval(pollTimerRef.current);
      }
    };

    pollStatus();
    pollTimerRef.current = setInterval(pollStatus, 1000);

    return () => {
      if (pollTimerRef.current) clearInterval(pollTimerRef.current);
    };
  }, [scanId, scanActive, router]);

  const resetScan = () => {
    if (pollTimerRef.current) clearInterval(pollTimerRef.current);
    if (scanDoneTimeoutRef.current) clearTimeout(scanDoneTimeoutRef.current);
    setScanBarWidth(0);
    setScanStepText("Initializing...");
    setScanStepIndex(-1);
    setScanError(null);
    setScanId(null);
  };

  const advanceStep = (index: number) => {
    setScanStepText(SCAN_STEPS[index]);
    setScanBarWidth(SCAN_PCTS[index]);
    setScanStepIndex(index);
  };

  const runScan = async (rawUrl: string) => {
    const cleanUrl = rawUrl.trim().replace(/^https?:\/\//, "");

    setScanUrlDisplay(`https://${cleanUrl}`);
    setScanActive(true);

    resetScan();

    if (!cleanUrl) {
      setScanError("URL is required");
      setScanStepText("✗ Error: URL is required");
      return;
    }

    setScanStepText("Starting scan...");

    try {
      const response = await fetch("/api/scan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: cleanUrl }),
      });

      const data = await response.json();

      if (!response.ok || !data.scanId) {
        throw new Error(data.error || "Failed to start scan");
      }

      setScanId(data.scanId);
      advanceStep(0);
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to start scan";
      setScanError(message);
      setScanStepText(`✗ Error: ${message}`);
    }
  };

  const closeScan = () => {
    if (pollTimerRef.current) clearInterval(pollTimerRef.current);
    if (scanDoneTimeoutRef.current) clearTimeout(scanDoneTimeoutRef.current);
    setScanActive(false);
    setScanId(null);
  };

  const toggleFaq = (index: number) => {
    setOpenFaqIndex((prev) => (prev === index ? null : index));
  };

  return (
    <>
      <nav>
        <a href="#" className="nav-logo">
          <span className="dot" />
          AuditAI
        </a>
        <ul className="nav-links">
          <li>
            <a href="#features">Features</a>
          </li>
          <li>
            <a href="#how">How it works</a>
          </li>
          <li>
            <a href="#pricing">Pricing</a>
          </li>
          <li>
            <a href="#faq">FAQ</a>
          </li>
        </ul>
        <a href="#" className="nav-cta">
          Free scan →
        </a>
      </nav>

      <div style={{ maxWidth: "1100px", margin: "0 auto", position: "relative" }}>
        <section
          className="hero"
          style={{ maxWidth: "none", paddingRight: "380px" }}
        >
          <div className="hero-badge">AI Search Readiness Scanner</div>
          <h1 className="hero-headline">
            Is ChatGPT ignoring
            <br />
            <em>your website?</em>
          </h1>
          <p className="hero-sub">
            Run a 60-second AI audit. Find out exactly why AI search engines skip your
            content — and get the precise fixes to start getting cited.
          </p>
          <div className="hero-input-wrap">
            <span className="url-prefix">https://</span>
            <input
              type="text"
              id="url-input"
              placeholder="yourwebsite.com"
              autoComplete="off"
              spellCheck={false}
              value={heroUrl}
              onChange={(e) => setHeroUrl(e.target.value)}
            />
            <button className="scan-btn" onClick={() => runScan(heroUrl)}>
              Scan now
            </button>
          </div>
          <p className="hero-note">
            Free scan available → <span>No account required</span>
          </p>
        </section>

        <div className="hero-visual">
          <div className="score-card">
            <div className="score-url">example-site.com</div>
            <div className="score-main">
              <div className="score-num" id="hero-score">
                {heroScore}
              </div>
              <div>
                <div className="score-label">
                  AI readiness
                  <br />
                  score
                </div>
              </div>
            </div>
            <div className="pillars">
              {HERO_PILLARS.map((pillar, index) => (
                <div className="pillar-row" key={pillar.name}>
                  <span className="pillar-name">{pillar.name}</span>
                  <div className="pillar-bar">
                    <div
                      className="pillar-fill"
                      style={{
                        width: `${pillarWidths[index]}%`,
                        background: pillar.color,
                      }}
                    />
                  </div>
                  <span className="pillar-score">{pillarScores[index]}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <div className="trust-bar">
        <div className="trust-item">
          <strong>2,847</strong> sites scanned today
        </div>
        <div className="trust-sep" />
        <div className="trust-item">
          <strong>30+</strong> AI-specific checks
        </div>
        <div className="trust-sep" />
        <div className="trust-item">
          Works with <strong>ChatGPT · Perplexity · Gemini · Claude</strong>
        </div>
        <div className="trust-sep" />
        <div className="trust-item">
          Results in <strong>&lt; 60 seconds</strong>
        </div>
      </div>

      <section id="features">
        <div className="section-label reveal">What we analyze</div>
        <h2 className="section-title reveal">
          Four pillars that
          <br />
          determine <em>AI visibility</em>
        </h2>
        <p className="section-sub reveal">
          Most SEO tools were built for Google crawlers. We&apos;re built for how language
          models actually read, understand, and cite content.
        </p>

        <div className="pillars-grid">
          <div className="pillar-card reveal">
            <div className="pillar-index">01 / Schema Markup</div>
            <div className="pillar-icon">⬡</div>
            <h3>Structured Data</h3>
            <p>
              AI engines rely on structured data to understand what your content is
              about before reading a single word.
            </p>
            <ul className="pillar-checks">
              <li>JSON-LD validation &amp; completeness</li>
              <li>Article schema with author credentials</li>
              <li>FAQ schema for direct AI extraction</li>
              <li>Organization &amp; BreadcrumbList schema</li>
              <li>Open Graph optimization</li>
            </ul>
          </div>
          <div className="pillar-card reveal">
            <div className="pillar-index">02 / Content Quality</div>
            <div className="pillar-icon">◈</div>
            <h3>AI Digestibility</h3>
            <p>
              LLMs cite content that&apos;s structured for comprehension — clear hierarchy,
              direct answers, factual density.
            </p>
            <ul className="pillar-checks">
              <li>Heading hierarchy analysis</li>
              <li>FAQ &amp; Q&amp;A format detection</li>
              <li>Answer-focused content scoring</li>
              <li>Factual density measurement</li>
              <li>Author attribution &amp; expertise</li>
            </ul>
          </div>
          <div className="pillar-card reveal">
            <div className="pillar-index">03 / Technical SEO</div>
            <div className="pillar-icon">◻</div>
            <h3>AI Crawlability</h3>
            <p>
              If AI crawlers can&apos;t access or parse your site efficiently, your content
              might as well not exist.
            </p>
            <ul className="pillar-checks">
              <li>Page speed for crawler efficiency</li>
              <li>Mobile-first optimization</li>
              <li>Semantic HTML structure</li>
              <li>Robots.txt &amp; sitemap audit</li>
              <li>Clean URL &amp; internal linking</li>
            </ul>
          </div>
          <div className="pillar-card reveal">
            <div className="pillar-index">04 / Trust Signals</div>
            <div className="pillar-icon">◇</div>
            <h3>E-A-T Factors</h3>
            <p>
              AI models are trained to evaluate expertise, authority, and
              trustworthiness before citing a source.
            </p>
            <ul className="pillar-checks">
              <li>About page completeness</li>
              <li>Contact info &amp; business legitimacy</li>
              <li>Legal pages &amp; compliance</li>
              <li>Author profiles &amp; credentials</li>
              <li>Social proof &amp; citations</li>
            </ul>
          </div>
        </div>
      </section>

      <div className="how-full" style={{ background: "var(--bg2)" }}>
        <div className="how-inner" id="how">
          <div className="section-label reveal">Process</div>
          <h2 className="section-title reveal">
            Three steps to
            <br />
            <em>AI-ready</em> content
          </h2>

          <div className="steps">
            <div className="step reveal">
              <div className="step-num">01</div>
              <h3>Enter your URL</h3>
              <p>
                Paste any publicly accessible URL. We&apos;ll fetch and render your page
                exactly as AI crawlers see it — including JavaScript-rendered content.
              </p>
            </div>
            <div className="step reveal">
              <div className="step-num">02</div>
              <h3>We run 30+ checks</h3>
              <p>
                Our engine analyzes schema markup, content structure, technical signals,
                and trust factors across all four pillars in under 60 seconds.
              </p>
            </div>
            <div className="step reveal">
              <div className="step-num">03</div>
              <h3>Get your fix plan</h3>
              <p>
                Receive a prioritized list of issues with exact fix instructions —
                copy-paste schema code, content templates, and implementation guides.
              </p>
            </div>
          </div>
        </div>
      </div>

      <section>
        <div className="section-label reveal">By the numbers</div>
        <h2 className="section-title reveal">
          The AI search
          <br />
          revolution is <em>now</em>
        </h2>

        <div className="stats-grid">
          <div className="stat-box reveal">
            <span className="stat-big">89%</span>
            <span className="stat-desc">
              Of searches now involve AI-powered engines or assistants
            </span>
          </div>
          <div className="stat-box reveal">
            <span className="stat-big">5×</span>
            <span className="stat-desc">
              More organic traffic for sites optimized for AI citation
            </span>
          </div>
          <div className="stat-box reveal">
            <span className="stat-big">73%</span>
            <span className="stat-desc">
              Of websites currently fail basic AI readiness checks
            </span>
          </div>
          <div className="stat-box reveal">
            <span className="stat-big">30+</span>
            <span className="stat-desc">
              AI-specific checks run across all four optimization pillars
            </span>
          </div>
        </div>
      </section>

      <section id="pricing" style={{ paddingTop: 0 }}>
        <div className="section-label reveal">Pricing</div>
        <h2 className="section-title reveal">
          Simple, transparent
          <br />
          <em>pricing</em>
        </h2>
        <p className="section-sub reveal">
          Start free. Go deep when you&apos;re ready. No subscriptions, no lock-in.
        </p>

        <div className="pricing-grid">
          <div className="price-card reveal">
            <div className="price-tag">FREE</div>
            <div className="price-name">Quick scan</div>
            <div className="price-amount">
              <span className="price-dollar">$</span>
              <span className="price-num">0</span>
            </div>
            <div className="price-per">always free</div>
            <div className="price-desc">
              Get your overall AI readiness score and top-level pillar breakdown —
              instantly.
            </div>
            <ul className="price-features">
              <li>
                <span className="check">✓</span> Overall AI readiness score
              </li>
              <li>
                <span className="check">✓</span> Pillar breakdown (4 scores)
              </li>
              <li>
                <span className="check">✓</span> Top 3 critical issues
              </li>
              <li>
                <span className="cross">–</span> Detailed fix instructions
              </li>
              <li>
                <span className="cross">–</span> Schema code snippets
              </li>
              <li>
                <span className="cross">–</span> PDF report download
              </li>
            </ul>
            <a href="#" className="price-btn">
              Run free scan
            </a>
          </div>
          <div className="price-card featured reveal">
            <div className="price-tag">MOST POPULAR</div>
            <div className="price-name">Full audit</div>
            <div className="price-amount">
              <span
                className="price-dollar"
                style={{ textDecoration: "line-through", opacity: 0.65 }}
              >
                $29
              </span>
              <span className="price-dollar">$</span>
              <span className="price-num">0</span>
            </div>
            <div className="price-per">limited time offer</div>
            <div className="price-desc">
              Everything you need to fix your AI visibility — with exact code,
              templates, and a priority action plan.
            </div>
            <ul className="price-features">
              <li>
                <span className="check">✓</span> Full AI readiness score
              </li>
              <li>
                <span className="check">✓</span> All 30+ issue details
              </li>
              <li>
                <span className="check">✓</span> Priority fix roadmap
              </li>
              <li>
                <span className="check">✓</span> Copy-paste schema code
              </li>
              <li>
                <span className="check">✓</span> PDF report download
              </li>
              <li>
                <span className="check">✓</span> 30-day re-scan access
              </li>
            </ul>
            <a href="#" className="price-btn primary">
              Get full audit — $0 (limited time)
            </a>
          </div>
          <div className="price-card reveal">
            <div className="price-tag">PREMIUM</div>
            <div className="price-name">Premium</div>
            <div className="price-amount">
              <span className="price-num" style={{ fontSize: "36px" }}>
                Coming soon
              </span>
            </div>
            <div className="price-per">launching soon</div>
            <div className="price-desc">
              Perfect for agencies and consultants managing multiple client websites.
            </div>
            <ul className="price-features">
              <li>
                <span className="check">✓</span> 10 full audit credits
              </li>
              <li>
                <span className="check">✓</span> Credits never expire
              </li>
              <li>
                <span className="check">✓</span> All full audit features
              </li>
              <li>
                <span className="check">✓</span> Shareable report links
              </li>
              <li>
                <span className="check">✓</span> White-label PDF option
              </li>
              <li>
                <span className="check">✓</span> Priority support
              </li>
            </ul>
            <a href="#" className="price-btn">
              Coming soon
            </a>
          </div>
        </div>
      </section>

      <section id="faq" style={{ paddingTop: 0 }}>
        <div className="section-label reveal">FAQ</div>
        <h2 className="section-title reveal">
          Common <em>questions</em>
        </h2>

        <div className="faq-list reveal">
          {FAQ_ITEMS.map((item, index) => {
            const isOpen = openFaqIndex === index;

            return (
              <div
                key={item.q}
                className={`faq-item${isOpen ? " open" : ""}`}
              >
                <div className="faq-q" onClick={() => toggleFaq(index)}>
                  {item.q}
                  <span className="faq-icon">+</span>
                </div>
                <div className="faq-a">{item.a}</div>
              </div>
            );
          })}
        </div>
      </section>

      <div className="cta-full" style={{ background: "var(--bg2)" }}>
        <div className="cta-inner">
          <h2 className="cta-title reveal">
            Start getting cited by
            <br />
            <em>ChatGPT</em> today
          </h2>
          <p className="cta-sub reveal">
            Free scan takes 60 seconds. No account needed. Find out where you stand
            right now.
          </p>
          <div className="cta-input-wrap reveal">
            <input
              type="text"
              className="cta-input"
              id="cta-url-input"
              placeholder="yourwebsite.com"
              autoComplete="off"
              spellCheck={false}
              value={ctaUrl}
              onChange={(e) => setCtaUrl(e.target.value)}
            />
            <button className="cta-scan-btn" onClick={() => runScan(ctaUrl)}>
              Scan now →
            </button>
          </div>
        </div>
      </div>

      <footer>
        <div className="footer-logo">AuditAI // AI Search Optimization</div>
        <ul className="footer-links">
          <li>
            <a href="#">Features</a>
          </li>
          <li>
            <a href="#">Pricing</a>
          </li>
          <li>
            <a href="#">Blog</a>
          </li>
          <li>
            <a href="#">Affiliate program</a>
          </li>
          <li>
            <a href="#">Privacy policy</a>
          </li>
          <li>
            <a href="#">Terms</a>
          </li>
        </ul>
        <div className="footer-copy">© 2026 AuditAI. All rights reserved.</div>
      </footer>

      <div
        className={`scan-overlay${scanActive ? " active" : ""}`}
        id="scan-overlay"
        onClick={closeScan}
      >
        <div className="scan-modal" onClick={(e) => e.stopPropagation()}>
          <div className="scan-modal-label">{"// SCANNING IN PROGRESS"}</div>
          <h2>Analyzing your site</h2>
          <div className="scan-modal-url" id="scan-url-display">
            {scanUrlDisplay}
          </div>

          <div className="scan-progress-wrap">
            <div className="scan-step-current" id="scan-step-text">
              {scanStepText}
            </div>
            <div className="scan-bar-bg">
              <div
                className="scan-bar-fill"
                id="scan-bar"
                style={{ width: `${scanBarWidth}%` }}
              />
            </div>
          </div>

          <ul className="scan-steps-list" id="scan-steps">
            {SCAN_STEPS.map((step, index) => {
              const isDone = index < scanStepIndex;
              const isActive = index === scanStepIndex;

              return (
                <li
                  key={step}
                  className={`scan-step-item${isDone ? " done" : ""}${
                    isActive ? " active" : ""
                  }`}
                  data-step={index}
                >
                  <span className="scan-step-icon">
                    {isDone ? "✓" : isActive ? "›" : "○"}
                  </span>
                  {step}
                </li>
              );
            })}
          </ul>
          {scanError && (
            <div className="scan-step-current" style={{ marginTop: "12px", marginBottom: "0" }}>
              {scanError}
            </div>
          )}
        </div>
      </div>
    </>
  );
}
