"use client";

import { useState, useRef, useEffect } from "react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger);
}

const faqs = [
  {
    q: "How is this different from traditional SEO tools like Ahrefs or Semrush?",
    a: "Traditional SEO tools optimize for Google's PageRank algorithm — backlinks, keyword density, crawl budget. AI search engines like ChatGPT and Perplexity work completely differently. They parse content semantically, rely heavily on structured data, and evaluate authority through E-A-T signals. We're built specifically for this new paradigm.",
  },
  {
    q: "What exactly do I get with the $29 full audit?",
    a: "You get a detailed breakdown of all 30+ checks across the four pillars, a prioritized fix roadmap, copy-paste JSON-LD schema code tailored to your site, content structure recommendations, and a downloadable PDF report. You also get 30-day access to re-scan after making changes.",
  },
  {
    q: "Which AI search engines does this optimize for?",
    a: "Our checks are validated against ChatGPT's browsing behavior, Perplexity's citation patterns, Google's SGE (AI Overviews), Microsoft Copilot, and Claude. The underlying optimization principles — structured data, semantic clarity, authority signals — apply across all major AI search platforms.",
  },
  {
    q: "Can you scan JavaScript-rendered websites?",
    a: "Yes. We use a full headless rendering pipeline so we see your site exactly as AI crawlers do — including content generated by React, Vue, Next.js, or any other JavaScript framework. Static HTML sites are also fully supported.",
  },
  {
    q: "Is the free scan actually useful or just a teaser?",
    a: 'The free scan gives you your real score and identifies your top 3 critical issues — enough to understand where you stand and whether investing in the full audit makes sense. We deliberately make it useful, not a fake preview. If your site scores 85+, you probably don\'t need to pay.',
  },
  {
    q: "What's your refund policy?",
    a: "We offer a full refund within 48 hours if the audit doesn't surface any actionable issues for your site. Given that 73% of sites fail basic AI readiness checks, this is rare — but we stand behind it. Email us directly at support@auditai.com.",
  },
];

export default function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  const containerRef = useRef<HTMLElement>(null);
  const headerRef = useRef<HTMLDivElement>(null);
  const faqsRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current || !headerRef.current || !faqsRef.current) return;

    const ctx = gsap.context(() => {
      // Header Animation
      gsap.fromTo(
        headerRef.current!.children,
        { y: 50, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 1,
          stagger: 0.15,
          ease: "power3.out",
          scrollTrigger: {
            trigger: headerRef.current,
            start: "top 80%",
          }
        }
      );

      // FAQ Items Staggered Animation
      const items = gsap.utils.toArray(".faq-item");
      gsap.fromTo(
        items,
        { y: 30, opacity: 0 },
        {
          y: 0,
          opacity: 1,
          duration: 0.8,
          stagger: 0.1,
          ease: "power2.out",
          scrollTrigger: {
            trigger: faqsRef.current,
            start: "top 85%",
          }
        }
      );
    }, containerRef);

    return () => ctx.revert();
  }, []);

  const toggle = (i: number) => {
    setOpenIndex(openIndex === i ? null : i);
  };

  return (
    <section id="faq" ref={containerRef} className="site-container site-section-bottom relative z-[1] max-w-[1000px]">
      
      <div ref={headerRef} className="mb-20 text-center">
        <div className="font-mono text-[13px] tracking-[0.15em] text-accent uppercase mb-6 inline-block bg-accent/10 px-4 py-1.5 rounded-full border border-accent/20">
          FAQ
        </div>
        <h2
          className="font-serif leading-[1.1] tracking-[-0.02em]"
          style={{ fontSize: "clamp(2.5rem, 5vw, 4rem)" }}
        >
          Common <em className="italic text-accent">questions</em>
        </h2>
      </div>

      <div ref={faqsRef} className="flex flex-col gap-4">
        {faqs.map((faq, i) => {
          const isOpen = openIndex === i;
          return (
            <div
              key={i}
              className="faq-item glass-panel rounded-xl overflow-hidden transition-all duration-300"
              style={{
                borderColor: isOpen ? "rgba(168,255,87,0.3)" : "rgba(255,255,255,0.05)",
                background: isOpen ? "rgba(24,24,24,0.6)" : "rgba(17,17,17,0.4)"
              }}
            >
              <div
                className="flex justify-between items-center px-8 py-7 cursor-pointer text-[16px] font-medium select-none gap-6 hover:text-white"
                onClick={() => toggle(i)}
              >
                <span className="leading-[1.5]">{faq.q}</span>
                <span
                  className="w-8 h-8 rounded-full border border-white/10 flex items-center justify-center shrink-0 transition-transform duration-500 ease-out"
                  style={{
                    transform: isOpen ? "rotate(135deg)" : "rotate(0deg)",
                    background: isOpen ? "rgba(168,255,87,0.1)" : "transparent",
                    borderColor: isOpen ? "rgba(168,255,87,0.3)" : "rgba(255,255,255,0.1)",
                    color: isOpen ? "var(--accent)" : "white"
                  }}
                >
                  <svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
                    <path d="M6 1V11M1 6H11" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/>
                  </svg>
                </span>
              </div>
              <div
                className="text-[15px] text-muted leading-[1.9] px-8 overflow-hidden transition-all duration-500 cubic-bezier(0.16, 1, 0.3, 1)"
                style={{
                  maxHeight: isOpen ? "400px" : "0",
                  paddingBottom: isOpen ? "32px" : "0",
                  opacity: isOpen ? 1 : 0
                }}
              >
                {faq.a}
              </div>
            </div>
          );
        })}
      </div>
    </section>
  );
}
